#!/bin/bash
#SBATCH --partition=normal
#SBATCH --export=NONE
#SBATCH --time=48:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=6G
#SBATCH --output="%x.o%j"
#SBATCH --error="%x.e%j"

SAMPLENAME=XXSAMPLENAMEXX
WORKDIR=XXWORKDIRXX
GENOME=XXGENOMEXX
SINGLETS=qc_DoubletFinder_pass_singlets.txt
INFILE=${SAMPLENAME}.csv

cd $WORKDIR

module load cellranger

cellranger reanalyze \
  --id=${SAMPLENAME}_singlets \
  --agg=${INFILE} \
  --barcodes=${WORKDIR}/${SAMPLENAME}/${SINGLETS} \
  --matrix=${WORKDIR}/${SAMPLENAME}/outs/count/raw_feature_bc_matrix.h5 \
  --localcores=16 --localmem=96
