#!/bin/bash
#SBATCH --partition=normal
#SBATCH --export=NONE
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4G
#SBATCH --output="%x.o%j"
#SBATCH --error="%x.e%j"

SAMPLENAME=XXSAMPLENAMEXX
SAMPLEID=XXSAMPLEIDXX
WORKDIR=XXWORKDIRXX
FASTQDIR=XXFASTQDIRXX
GENOME=XXGENOMEXX
REFDATA=/s1/opt/cellranger-atac-2.1.0/refdata-cellranger-arc-${GENOME}-2020-A-2.0.0

cd $WORKDIR

module load cellranger-atac

cellranger-atac count \
  --id=${SAMPLENAME} \
  --sample=${SAMPLEID} \
  --reference=${REFDATA} \
  --fastqs=${FASTQDIR} \
  --localcores=32 --localmem=128
