#!/bin/bash
#SBATCH --partition=normal
#SBATCH --export=NONE
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4G
#SBATCH --output="%x.o%j"
#SBATCH --error="%x.e%j"

SAMPLENAME=XXSAMPLENAMEXX
WORKDIR=XXWORKDIRXX
GENOME=XXGENOMEXX
INFILE=${SAMPLENAME}.csv
REFDATA=/s1/opt/cellranger-arc-2.0.1/refdata-cellranger-arc-${GENOME}-2020-A-2.0.0

cd $WORKDIR

module load cellranger-arc

cellranger-arc aggr \
  --id=${SAMPLENAME} \
  --csv=${INFILE} \
  --reference=${REFDATA} \
  --localcores=32 --localmem=128
