#!/bin/bash
#SBATCH --partition=normal
#SBATCH --export=NONE
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8G
#SBATCH --output="%x.o%j"
#SBATCH --error="%x.e%j"

SAMPLENAME=XXSAMPLENAMEXX
FASTQFILE=XXFASTQFILEXX
WORKDIR=XXWORKDIRXX
GENOME=XXGENOMEXX
FASTQFOLDER=XXFASTQFOLDERXX

GENOMEINDEX=/s1/share/hisat2_indexes/${GENOME}/genome
SAMFILE=accepted_hits.sam
QUALBAMFILE=accepted_hits_mapq10.bam
SORTBAMFILE=accepted_hits_mapq10_sort.bam
COUNTSFILE=htseq_counts.txt

GTFFILE=/s1/share/UCSC_Downloads/${GENOME}/refGene_${GENOME}.gtf

module load hisat2
module load samtools
module load python/2.7.5

cd $WORKDIR
mkdir -p $SAMPLENAME

hisat2 -p 8 -5 10 -S ${SAMPLENAME}/${SAMFILE} -x $GENOMEINDEX -U ${FASTQFOLDER}/${FASTQFILE}
ln -s ${SAMPLENAME}/${COUNTSFILE} ${SAMPLENAME}_counts.txt
ln -s ${SAMPLENAME}/${SORTBAMFILE} ${SAMPLENAME}.bam

cd $SAMPLENAME
samtools view -bS -q 10 ${SAMFILE} > ${QUALBAMFILE}
samtools sort -o ${SORTBAMFILE} -T sort ${QUALBAMFILE}
htseq-count -f bam -r pos --stranded=reverse $SORTBAMFILE $GTFFILE > $COUNTSFILE

