#!/bin/bash
#SBATCH --partition=normal
#SBATCH --export=NONE
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8G
#SBATCH --output="%x.o%j"
#SBATCH --error="%x.e%j"

WORKDIR=XXWORKDIRXX
EXPERIMENT=XXEXPERIMENTXX

module load R

cd $WORKDIR

CONTROLSTR=$(head -1 ${EXPERIMENT}.txt | sed s/_rep[0-9]//)
CONTROLNUM=$(grep "$CONTROLSTR" ${EXPERIMENT}.txt | wc -l)
TREATSTR=$(grep -v "$CONTROLSTR" ${EXPERIMENT}.txt | head -1 | sed s/_rep[0-9]//)

sh makeDESeq2Table.sh ${EXPERIMENT}.txt ${EXPERIMENT}

cd ${EXPERIMENT}

Rscript ../DESeq2_compare_control_treat.R sampleTable.txt ${CONTROLNUM}

# make peak calls (increased, decreased, unchanged) based on DESeq2 output
PTHRESH=0.10
FTHRESH=0.58496250072
cat diffexpr-results.txt | awk -v pthresh=$PTHRESH -v fthresh=$FTHRESH 'BEGIN{OFS="\t"; FS="\t" } NR > 1 { if($7 < pthresh && $3 <= -fthresh) print $9,$10,$11,$8,$7,$3 }' > treat-decreased.bed
cat diffexpr-results.txt | awk -v pthresh=$PTHRESH -v fthresh=$FTHRESH 'BEGIN{OFS="\t"; FS="\t" } NR > 1 { if($7 < pthresh && $3 >= fthresh) print $9,$10,$11,$8,$7,$3 }' > treat-increased.bed
cat diffexpr-results.txt | awk -v pthresh=$PTHRESH -v fthresh=$FTHRESH 'BEGIN{OFS="\t"; FS="\t" } NR > 1 { if($7 > pthresh || $7 == "NA" || ($3 > -fthresh && $3 < fthresh)) print $9,$10,$11,$8,$7,$3 }' > unchanged.bed

# ranking and GSEA analysis
cat diffexpr-results.txt | awk 'BEGIN{FS=OFS="\t"}NR==1{print "#NAME","log2FoldChange"}NR>1{print toupper($8),$3}' | grep -vw "NA" > gseaData.rnk
Rscript ../gsea_basic.R

cd ..
