#!/bin/bash
#SBATCH --partition=normal
#SBATCH --export=NONE
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4G
#SBATCH --output="%x.o%j"
#SBATCH --error="%x.e%j"

SAMPLENAME=XXSAMPLENAMEXX
WORKDIR=XXWORKDIRXX
FASTQDIR=XXFASTQDIRXX
GENOME=XXGENOMEXX
REFDATA=/s1/opt/cellranger-5.0.1/refdata-gex-${GENOME}-2020-A

cd $WORKDIR

module load cellranger

cellranger count \
  --id=${SAMPLENAME} \
  --sample=${SAMPLENAME} \
  --transcriptome=${REFDATA} \
  --fastqs=${FASTQDIR} \
  --localcores=32 --localmem=128
